# Generated by Django 3.0.8 on 2020-07-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['name'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RenameField(
            model_name='bb',
            old_name='title',
            new_name='name',
        ),
    ]
